spring:
  thymeleaf:
    cache: false

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:  #指定Mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: on  #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: zust.competition.sys